-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Department"
(
    id integer NOT NULL,
    name character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE public."Employers"
(
    id integer NOT NULL,
    "Company_Name" character varying(70),
    "WebSite" character varying(70),
    telephone character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE public."JobSeekers"
(
    "id " integer NOT NULL,
    tckn character varying(11),
    name character varying(50),
    surname character varying(50),
    "departmentId" character varying(50),
    PRIMARY KEY ("id ")
);

CREATE TABLE public."SystemEmployer"
(
    id integer NOT NULL,
    name character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE public."Users"
(
    id integer NOT NULL,
    email character varying(50),
    password character varying(50),
    approved character varying(50),
    PRIMARY KEY (id)
);

ALTER TABLE public."Employers"
    ADD FOREIGN KEY (id)
    REFERENCES public."JobSeekers" ("id ")
    NOT VALID;


ALTER TABLE public."Users"
    ADD FOREIGN KEY (id)
    REFERENCES public."JobSeekers" ("id ")
    NOT VALID;


ALTER TABLE public."SystemEmployer"
    ADD FOREIGN KEY (id)
    REFERENCES public."JobSeekers" ("id ")
    NOT VALID;


ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY ("departmentId")
    REFERENCES public."Department" (id)
    NOT VALID;

END;